// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBl4-ThLsRjHbDCKZ9FezL7YJQ4G_YFDFw',
    appId: '1:585867791362:web:b3aaead080530aee1ceb1b',
    messagingSenderId: '585867791362',
    projectId: 'ridemate-7e08d',
    authDomain: 'ridemate-7e08d.firebaseapp.com',
    storageBucket: 'ridemate-7e08d.firebasestorage.app',
    measurementId: 'G-C3L1RKFQRX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQd6RYRUhvYFNV0IDhhcOekZSpp1DhaAE',
    appId: '1:585867791362:android:2b0e4a676c36cc071ceb1b',
    messagingSenderId: '585867791362',
    projectId: 'ridemate-7e08d',
    storageBucket: 'ridemate-7e08d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhD5A2n5yeeoUJP-8lO28DTDXRwpzpxK8',
    appId: '1:585867791362:ios:932e8b6a3035e2cf1ceb1b',
    messagingSenderId: '585867791362',
    projectId: 'ridemate-7e08d',
    storageBucket: 'ridemate-7e08d.firebasestorage.app',
    iosBundleId: 'com.example.ridemate.rideMate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhD5A2n5yeeoUJP-8lO28DTDXRwpzpxK8',
    appId: '1:585867791362:ios:932e8b6a3035e2cf1ceb1b',
    messagingSenderId: '585867791362',
    projectId: 'ridemate-7e08d',
    storageBucket: 'ridemate-7e08d.firebasestorage.app',
    iosBundleId: 'com.example.ridemate.rideMate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBl4-ThLsRjHbDCKZ9FezL7YJQ4G_YFDFw',
    appId: '1:585867791362:web:864cf8dcf3f3bae31ceb1b',
    messagingSenderId: '585867791362',
    projectId: 'ridemate-7e08d',
    authDomain: 'ridemate-7e08d.firebaseapp.com',
    storageBucket: 'ridemate-7e08d.firebasestorage.app',
    measurementId: 'G-4V45PEM3C6',
  );
}
